### ISSUE TITLE
Do you have the code for Low-rank Bilinear Pooling Keras?

### ISSUE THREAD

**Issue by LZF-GUET** [Jumperkables/pooling_time#1]
Do you have the code for Low-rank Bilinear Pooling Keras?

**Comment by LZF-GUET** [comment]
Grassmann pooling

**Comment by Jumperkables** [comment]
I don't I'm afraid. I made a few Keras implementations of BLP techniques for a friend as I didn't see any Keras implementations at the time. I figured I'd share it with GitHub incase someone else would find it useful.

I'd encourage you to find an alternative repository with more fusion implementations that keep up with new techniques and definitions :)
